dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.7"

install:
  - pip install -e .

before_script:
  - pip install -r requirements.txt

script:
  - pwd
  - coverage run -m pytest

after_success:
  - coveralls

